### ISSUE TITLE
XPServ Initial Meeting 

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/IPR-XPSERV#1]
We had a skype call on 04-05-2019 with Nathan kumar from US and the team from Amitysoft introduced (includes KRJ, Srikanth, Johnson, Karthik and Suressh)

Goal: An Overview of the product idea conceived for development in SAAS model has been explained by KRJ and Srikanth
      The product idea formed will find applicabilty in multiple Scenarios like 

      - Maintainence of Equipments in Plant integrated with any ERP
      - Maintainence of Equipments supplied by OEMS directly or Outsourced to others
      - Maintainence of Equipments by service providers from large scale to smaall scale 
  
Intial Rollout: It is presumed that the development will cater to the small scale service providers and scale up in future to other scenarios
                The target for the first roll out is fixed at 15th Aug 2019

Platform: The following Platforms are explored to develop the App  
          ZOHO - Multiple functionality App platform provides facility for developing and hosting the Apps
          Odoo - This is somewhat similar to ZOHO the language used is Python
          Own development using python and hosting

Weekly call : SUN proposed to have a weekly call on Saturdays @ 9-00 to 10.30 Am IST 

Attaching the initial Documents related to product discussion 
[EAM Masters and Transaction list for Kanam.xlsx](https://github.com/astpl1998/IPR-XPSERV/files/3152566/EAM.Masters.and.Transaction.list.for.Kanam.xlsx)
[Enterprise.asset.management.docx](https://github.com/astpl1998/IPR-XPSERV/files/3152567/Enterprise.asset.management.docx)
[IPR fields design-Mobile.pptx](https://github.com/astpl1998/IPR-XPSERV/files/3152568/IPR.fields.design-Mobile.pptx)
[IPR-Maintenance Project Plan.pptx](https://github.com/astpl1998/IPR-XPSERV/files/3152569/IPR-Maintenance.Project.Plan.pptx)
[Maintenance Screen Details.pptx](https://github.com/astpl1998/IPR-XPSERV/files/3152570/Maintenance.Screen.Details.pptx)
[XpServ-UserStory.docx](https://github.com/astpl1998/IPR-XPSERV/files/3152571/XpServ-UserStory.docx)

Mail by KRJ after the Meeting is Quoted for reference
=======
Dear Team,

We made a good beginning on our product development initiative.  I am connecting the entire team through this email.
Suressh – Please create project in ADS and share details with the team for collaboration. Load all initial set of documents we have and provide an intro.
Srikanth – please share product feature/context document.
Karthick – Explore Zoho creator for the development. Our assumption is that Zoho will provide complete environment including payment way connectivity and hosting.
Johson – Lets have the person who will play the role of Product Champion into the team.
As decided let’s decide on the Minimum Viable Product that can be released on 15 Aug. We should also have clarity  on the technology architecture (zoho or otherwise)
SUN – Ganapathi, the person CCed in this email handles business & finance aspects. He will be part of our review team.

Thanks
======

Product Features Mail sent by Srikanth Quoted below

====== 
Functionality
1	Work Order Process (CRUDL) - Work-Flow and Transactions
2	Allocation/Return of Material and Planned and Actual Labour
3	Work Order Status Monitoring & Reporting
4	Easy to understand BI Reports/Dashboard On KPI for Maintenance Services
5	Invoice Generation
6	SMS & E-mail

Typical Features
	Online Work Order Page
	Automated Task Notifications
	Basic Task List Manager
	Task Status Updates
	Unlimited Task Types
	Notes History
	Easy to Search Filter
	Basic Reporting
	Customizable Request Page
	Reporting & Dashboards
	Unlimited Users
	Multi-Facilities Available
	Mobile App Access (unlimited users)
	Customer Support
	Advanced Work Orders
	Areas (allows for multi-facilities)
	Notification by Task Type
	Task Assignment
	Task Priority Settings
	Task Duration Monitoring
	Audit Logs
	Document Management
	Vendor Management
	Preventive Maintenance
	PM Library
	Asset Database List
	Asset Expense Tracking
	Asset Forecasting
	Asset Depreciation
	Parts & Inventory
	Housekeeping Module
	Fleet Management
	Customized Reporting
	Capital Planning
	Custom Fillable Forms
	Transaction and Expenses
	Warranty & Life Expectancy
	Asset Barcode Scanning
	Capital Planning
	Extra Document Space Storage
	Project Management
	Temperature Sensor Integration
	All Future Upgrades

======

**Comment by KRJ-Amitysoft** [comment]
Dear Team,

 

I propose the below functionality for MVP for 15 Aug 2019.

 


1

Billing for services


2

AMC contracts


3

AMC Billings


4

AMC services tracking


5

AMC reminders


6

Logging Service Requests/ Complaints from customers


7

Allotting request to technicians


8

Service execution & customer acknowledgement


9

Android mobile interface


10

Uploading current customer contacts,  current AMC details


11

Default templates for AMC based on different categories of service (AC/ Lifts…etc.,)


12

Service metrics for customer and service technicians

 

Any other functionality to which the above will depend to be developed too.

We can include a minimum set from the list of typical features mentioned below to improve user experience.

If we can have basic screen layouts considering the above, we will involve UX expert to finalize the screen design.

 

Can we have discussion on the above tomorrow?

 

Thanks

**Comment by astpl1998** [comment]
Meeting Clossed

**Comment by astpl1998** [comment]
Need Visibilty
