### ISSUE TITLE
Agenda for 31-08-2019 MOM

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/IPR-XPSERV#18]
Progress of Xpserv was discussed following points highlighted 

1. Need to find a solution for establishing connection to cloud server with browser security with APK Generation  we are experiencing CORS Error
2. Need to progress on repairs module full functionality with the proven browser with out security
3. Should go with Google cloud platform
4. Explore webhost paid platform to see whether the security problem gets resolved

**Comment by rajiamity** [comment]
Dear Bhuvana Mam,

I would like to share the Development activities for XpSerV to help plan to timing Action Plan in day and responsibility basis.  

Development Scope of XpSerV: 
(Using Tools: 
Ionic 4 Framework, 
Angular 7 Programing Language, 
CSS 3 Styling, 
MySQL DB, 
PHP 7.2 API)


1.	Create Pages using Ionic Framework  
(Directly start from here as Page Idea/details given by Ganeshwari)
2.	Create UI components using Ionic components and Angular 
3.	Display UI Components to fit the page using Ionic components and CSS Styling Properties
4.	Understand and list the Services need for any page like camera, SMS etc (which saves lot of manual work)
5.	Write the Service file separately for all the generic services using ionic and angular
6.	Relate each page with its service needs from service file using ionic and angular
7.	Understand the Database Connectivity to any module
8.	Create the Database tables inclusive of generating the timestamp details of actions using MySQL
9.	Write the API to connect the app actions to Database tables using PHP
10.	Compile and confirm each and every activity for its correctness using Ionic Commands
11.	Create APK for each versions using Ionic Commands
12.	Verify the APK in Devices with Hosting Servers
 
I Hope this will be useful. Kindly share your view points.

**Comment by KRJ-Amitysoft** [comment]
Dear Team,

 

We will have a sype call around 5.30 PM today to review the status.

Team - Pl confirm availability.

 

Thanks

Jay

**Comment by astpl1998** [comment]
Ok Sir I will be joining

 

Regards

Suressh.CG                      



Head - ERP Practice

Certifications: Certified RamcoERP Consultant- (Finance, Supplychain, Production, Enterprise Asset Management)

AmitySoft Technologies Pvt Ltd.,

Email:  <mailto:sharmilabk@amitysoft.in> suressh@amitysoft.com | Mobile: +91-9790789979

Telephone :+91-044 42035577 / 24328077

Skype: suressh.cg LinkedIn: suressh@amitysoft.com <mailto:suressh@amitysoft.com>  Twitter : @suresshcg

HO: 6/22,II Floor, Dhandapani Street, T.Nagar, Chennai - 600 017, India

Offices : Bangalore, Mumbai, Vadodara, Kochi.

 <http://www.amitysoft.com/> www.amitysoft.com

Enterprise Solutions: ERP, Data Analytics, IoT

Advisory & Technical Services: Enterprise Cyber Security, Quality Assurance & Testing,

Functional Sizing, CMMI/ISO

Training: Testing, Software Quality Management, Big Data, Info Security, ERP

Disclaimer: The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this e-mail by anyone else is unauthorized. If you have received this communication in error, please address with the subject heading "Received in error," send to info@amitysoft.com <mailto:info@amitysoft.com> , then delete the e-mail and destroy any copies of it. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. Any opinions or advice contained in this e-mail are subject to the terms and conditions expressed in the governing agreement between Amitysoft and the client. Opinions, conclusions and other information in this e-mail and any attachments that do not relate to the official business of Amitysoft Technologies are neither given nor endorsed by it.

 

Amitysoft Technologies cannot guarantee that the e-mail communications are secure or error-free, as information could be intercepted, corrupted, amended, lost, destroyed, arrive late or incomplete, or contain viruses.

**Comment by KRJ-Amitysoft** [comment]
I want entire team to join except Bhuvana who is under treatment.

Let us plan it for tomorrow?

Can the current status be listed for us to discuss?

Thanks

Jay

**Comment by astpl1998** [comment]
[XpSerV Detailed Plan_09 Sep 19.xlsx](https://github.com/astpl1998/IPR-XPSERV/files/3593785/XpSerV.Detailed.Plan_09.Sep.19.xlsx)

Uploaded the detailed action plan for Repair module for tday's discussion

**Comment by astpl1998** [comment]
Task Completed
