### ISSUE TITLE
Exploration of ZOHO as a Platform for XPSERV APP

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/IPR-XPSERV#2]
It is decided to explore ZOHO as a platform for developing XPSERV app as discussed Karthik to explore the ZOHO creator functionalities  and provide a feedback in the next meeting the suitablity of the platform for hosting the App

**Comment by astpl1998** [comment]
@karthikeyanamitysoft 
Please list done the points on which we need clarification from ZOHO

**Comment by stephendharmaraj** [comment]
1. Need to   generate automatically CC No
2. need to   hide Work Order report for users visable for manager or admin
3. Add   Button and new button and del button
4. Need to   generate automatically invoice number
5. Print   Invoice with Preview option
