### ISSUE TITLE
Transforming Minimum functionality requirement to functional design

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/IPR-XPSERV#3]
As proposed by KRJ-Amitysoft in the below mail quote we will proceed towards defining overall minimum plan and define the functional design which includes screen design with fields 
=====
Dear Team,

I propose the below functionality for MVP for 15 Aug 2019.
1 Billing for services
2 AMC contracts
3 AMC Billings
4 AMC services tracking
5 AMC reminders
6 Logging Service Requests/ Complaints from customers
7 Allotting request to technicians
8 Service execution & customer acknowledgement
9 Android mobile interface
10 Uploading current customer contacts,  current AMC details
11 Default templates for AMC based on different categories of service (AC/ Lifts…etc.,)
12 Service metrics for customer and service technicians

Any other functionality to which the above will depend to be developed too.

We can include a minimum set from the list of typical features mentioned below to improve user experience.

If we can have basic screen layouts considering the above, we will involve UX expert to finalize the screen design.
======

**Comment by astpl1998** [comment]
@maheshwaran-m Refer to our call as discussed following functionalities need to be defined 

1. Repairs 
----------
                 - Screen to input incidents by Customer  
                 - Suitable input fields to be decided
                 - Once input is done an acknowledgement to be sent to customer
                 - An Alert to be sent to the service provider
                 - And a work order to be generated automatically 
                 - On completion of work @ site customer acknowledgement / Feedback to be recorded
                 - Finally Billing for service and spares used to be generated
                 - Payment collected to be updated to track the outstanding

2. Maintenance
-----------------
                 - Inputs required to be designed to generate AMC which capture all SLAs
                 - Trigger to customer for AMC Acknowledgement
                 - Alert to service provider  before due date and automatic generation generation of work 
                    order
                 - Finally Billing for any additional spares used not covered under AMC to be generated
                 - Payment collected to be updated to track the outstanding

3. Installation
------------- -
                - Order recording from OEM / Dealer 
                - Automatic generation of Work order 
                - Upon execution completion acknowledgement / Feedback frrom Customer
                - Billing to be generated to customer
                - Against bill collection to be tracked

**Comment by maheshwaran-m** [comment]
Dear Karthi,

Herewith i have attached Repairs Screen and Fields details for your reference. If any clarification pls let me know immediately.

[IPR-Repairs Fields and screen details.pptx](https://github.com/astpl1998/IPR-XPSERV/files/3160601/IPR-Repairs.Fields.and.screen.details.pptx)

Regards,
M.Maheshwaran

**Comment by karthikeyanamitysoft** [comment]
Dear Stephen,

Kindly create new app for the logic given in the attached file.

REgards,
Karthi

**Comment by maheshwaran-m** [comment]
Dear Karthi,

Herewith i have attached Maintenance  Screen and Fields details for your reference. If any clarification pls let me know immediately.

[02_IPR-Maintenance screen and Fields design.pptx](https://github.com/astpl1998/IPR-XPSERV/files/3181108/02_IPR-Maintenance.screen.and.Fields.design.pptx)

Regards,
M.Maheshwaran
