### ISSUE TITLE
Meeting agenda 24-05-2019 10 AM IST

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/IPR-XPSERV#6]
General Points

1. Decision on acquiring Zoho platform for development under discussion
2. Architecting the app following points needs clarity
    - Amity develops the XPSERV App and host it on the cloud
    - Amity sells to customer "A"  which means the functionalities XPSERV is available for 
      Customer "A" for use  in 3 heads 1. Repairs 2. maintenance 3, Installation 
    - Clarification needed in Customer "A" 's Client logging in and launching a complaint in 
       mobile app for a repair
       This client may not be knowing the Customer A he logs in and type the complaint How this 
       complaint will reach Customer A when XPServ is shared by multiple customers need a 
       resolution for this point how to establish this link . 
    - Maintenance and installation how this could be esatblished using AMC or Order
3  - Listing from contacts needs further clarification
Points on Zoho Platform
     - Clarification needed on database access
     -  Access control
     - Screen Customisation
     - Scripting changes training 

Repairs 
    -  Review of screens developed in demo login
    -  points need to be validated 
          - Equipment in AMC to be tracked before booking it as repair 
          - Existing customers data should be loaded by default
          - Service Orders person and service location person can be different
     
Maintenance 
      - Review of Screens developed in demo login

**Comment by astpl1998** [comment]
MOM 24-05-2019

Participants : KRJ, Nathan, Suressh, Ganapathi, Menon Pai, Kalpana jayakumar

1. Discussed about the price model of Zoho further to be taken up with ZOHO to decide on a suitable price model

2. Dissussed on point of Archecting the app following decided for Aug 15th Delivery

1. Product owner
2.Service provider
3 Service User

The service provider purchases users from ZOHO and provide to their service Users so both are seamlessly linked please refer to the image attachedd below for the process flow

![image](https://user-images.githubusercontent.com/37649615/58384217-e01d1800-7ffc-11e9-88a8-1255c7a67caf.png)

II Phase to provide an app for anyuser to select service provider (This is not part of 15th Aug delivery)

**Comment by KRJ-Amitysoft** [comment]
Dear Team,

 

Pl find attached a doc on technology options for SaaS as discussed today. Let us also get more details for us to conclude on alternate technology platform, while we go ahead and develop our prototype in Zoho.

Thanks
