### ISSUE TITLE
Agenda for 21-06-2019 Meeting

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/IPR-XPSERV#9]
- Customer visit Overview By Karthick
- Exploration of Python and Flask - Stephen
- Exploration of Ionic Platform _ Rajalakshni
- Additonal points if any

**Comment by KRJ-Amitysoft** [comment]
Self and Ganapathi will be on listening mode, as we would in train.

Thanks

Jay

**Comment by astpl1998** [comment]
Karthick
Network Security
Language Flexibility
Portal to Upload Profile and offers
Maintain a Log of Customers 
Demo to Polytechnic Students
Stephen
projected the screens developed in Flask and Python
Database connect to Mysql
Raji
Exploring Ionic interface 
We be able to project her finding by next week
Additional Point
Nathan suggested to have scrum meeting daily and update in skype to get the feel of project movement
Pozzle app to be explored to get feel of the mobile app can be taken as baseline for app design

**Comment by astpl1998** [comment]
Discussed with Stephen regarding Progress and the repair use case completion
Following are the List which needs to be completed for repairs Use-case
- Identification of a framework which can have capabilities  to develop Web App and Mobile App
- Develop Screens as per "IPR-Repairs-Fieldsandsreen.details.PPTX" 
- Identification of a Database which could connect above identified frontend and backend   
- Test the entire flow end to end with all triggers mentioned in the PPTX

**Comment by astpl1998** [comment]
Review with Raji
IONIC capable of developing web- based and mobile based app simultaneously
i.e converting the web-based to Mobile based app using dev-apps which is part of IONIC  
So IONIC is capable of developing both web based and Mobile Based app simultaneously 
Showcased the developed screens for repair module in IONIC Platform
Exploring the logic of connecting to backend

**Comment by astpl1998** [comment]
Review with stephen 
Converting a webbased development to mobile APP is through APK extension how to do that in Flask framework needs to be explored

**Comment by astpl1998** [comment]
Task Completed

**Comment by astpl1998** [comment]
Task Completed
